"""Structure reading for the data audit: biological assemblies, zipped members, chain atoms.

Split out of audit_all_datasets.py, which re-exports every name here. Contact,
overlap and eligibility checks stay there because they read the cutoffs that
``main`` rebinds from the command line.
"""
from __future__ import annotations

import gzip
import hashlib
import math
import pathlib
import re
import threading
import zipfile
import gemmi
import numpy as np
from scipy.spatial import cKDTree
from nanoqc.structure.residue_tables import BACKBONE_ATOMS, SIDECHAIN_HEAVY_ATOMS

BACKBONE = set(BACKBONE_ATOMS)
SIDECHAIN_HEAVY = {name: set(atoms) for name, atoms in SIDECHAIN_HEAVY_ATOMS.items()}
ZIP_LOCAL = threading.local()


def pdb_compat(raw, task):
    try:
        return gemmi.read_pdb_string(raw)
    except RuntimeError as exc:
        if 'Wrong format for charge' not in str(exc):
            raise
        # Historic DB5.5 records retain obsolete PDB identifiers/line numbers
        # in columns 67+. Coordinates/occupancy/B-factor remain untouched.
        task['_legacy_pdb_tail'] = True
        return gemmi.read_pdb_string(raw, max_line_length=66)

# Subsets read from raw PDB entries (asymmetric unit). Following SAbDab and
# SNAC-DB [METHODS_EVIDENCE R33,R34], their complexes are taken from the
# biological assembly instead, so crystal-packing neighbours inside the ASU are
# not mistaken for antigen and partners generated by symmetry are not lost.
# snac_db files are already SNAC-DB assembly-curated complexes.
ASSEMBLY_SUBSETS = frozenset({'sabdab_vhh', 'train_rcsb'})
STRUCTURE_SOURCE_KEY = '_nanoqc_structure_source'
# RCSB serves a biological assembly as its own file, named <entry>_assembly<N>
# (also -assembly<N>, and .pdb<N> for the legacy format). Such a file already
# holds the assembled coordinates, so it carries no pdbx_struct_assembly: that
# record says how to BUILD an assembly from the asymmetric unit. Requiring it
# would reject a file that is already what the rule asks for, and applying a
# transform to it would build the assembly twice.
_PREBUILT_ASSEMBLY = re.compile(r'[-_]assembly(\d+)\.(?:cif|pdb)(?:\.gz)?$|\.pdb(\d+)$', re.IGNORECASE)


def prebuilt_assembly(name):
    """The assembly number when ``name`` is an RCSB assembly file, else None."""
    match = _PREBUILT_ASSEMBLY.search(pathlib.PurePosixPath(str(name)).name)
    return (match.group(1) or match.group(2)) if match else None


def biological_assembly_structure(st):
    """Return a one-model copy of ``st`` built from its biological assembly.

    Uses the first author-determined assembly (REMARK 350 /
    pdbx_struct_assembly), falling back to the first software-determined one;
    fails closed when the entry has no assembly annotation at all. Chains
    produced by an identity operator keep their author names (so chain
    annotations still match); symmetry copies are named ``<chain>-<operator>``.
    The choice is recorded in ``st.info[STRUCTURE_SOURCE_KEY]``.
    """
    assemblies = list(st.assemblies)
    if not assemblies:
        raise ValueError('no biological assembly annotation (REMARK 350/pdbx_struct_assembly); '
                         'cannot separate the biological complex from crystal contacts')
    author = [a for a in assemblies if a.author_determined]
    chosen = (author or assemblies)[0]
    basis = 'author_determined' if author else ('software_determined' if chosen.software_determined else 'unspecified')
    st.setup_entities()
    source = st[0]
    built = {}
    for generator in chosen.generators:
        subchains = set(generator.subchains)
        chains = set(generator.chains)
        for operator in generator.operators:
            identity = operator.transform.is_identity()
            for chain in source:
                residues = [res for res in chain
                            if (res.subchain in subchains if subchains else chain.name in chains)]
                if not residues:
                    continue
                name = chain.name if identity else f'{chain.name}-{operator.name}'
                target = built.setdefault(name, gemmi.Chain(name))
                for res in residues:
                    copy = res.clone()
                    if not identity:
                        for atom in copy:
                            atom.pos = gemmi.Position(operator.transform.apply(atom.pos))
                    target.add_residue(copy)
    if not built:
        raise ValueError(f'biological assembly {chosen.name} selects no chains')
    result = st.clone()
    while len(result):
        del result[0]
    model = gemmi.Model('1')
    for chain in built.values():
        model.add_chain(chain)
    result.add_model(model)
    result.setup_entities()
    result.info[STRUCTURE_SOURCE_KEY] = f'biological_assembly:{basis}:{chosen.name}'
    return result


def materialize_graph_complex(source_path, graph, destination):
    """Rebuild, from the raw source file, exactly the complex a graph encodes.

    Re-applies the graph's recorded biological-assembly choice and keeps only
    ``graph.chain_ids``, so all-atom consumers (energy calibration, validation
    targets) score the same chains the graph and its labels were built from.
    Returns ``source_path`` untouched when no change is needed.
    """
    recorded = str(getattr(graph, 'structure_source', '') or '')
    if not recorded:
        raise ValueError('graph lacks structure_source provenance; rebuild graphs (v1.10)')
    st = gemmi.read_structure(str(source_path))
    if not len(st):
        raise ValueError('source structure has no coordinate model')
    while len(st) > 1:
        del st[1]
    changed = False
    if recorded.startswith('biological_assembly:'):
        st = biological_assembly_structure(st)
        if dict(st.info).get(STRUCTURE_SOURCE_KEY) != recorded:
            raise ValueError(f'assembly choice {dict(st.info).get(STRUCTURE_SOURCE_KEY)} differs from graph provenance {recorded}')
        changed = True
    keep = set(graph.chain_ids)
    present = {chain.name for chain in st[0]}
    if keep - present:
        raise ValueError(f'graph chains missing from rebuilt source: {sorted(keep - present)}')
    for index in reversed(range(len(st[0]))):
        if st[0][index].name not in keep:
            del st[0][index]
            changed = True
    if not changed:
        return source_path
    st.setup_entities()
    st.make_mmcif_document().write_file(str(destination))
    return destination


def read_structure(task):
    st, multi = _read_raw_structure(task)
    assembly = prebuilt_assembly(task['member'] or task['path'])
    if task.get('subset') not in ASSEMBLY_SUBSETS:
        st.info[STRUCTURE_SOURCE_KEY] = 'as_deposited_file'
    elif assembly is not None:
        # Already the assembly: never transform it again.
        st.info[STRUCTURE_SOURCE_KEY] = f'prebuilt_assembly_file:assembly{assembly}'
    else:
        st = biological_assembly_structure(st)
    return st, multi


def _read_raw_structure(task):
    name = task['member'] or task['path']
    if not task['member'] and not name.lower().endswith('.pdb'):
        return gemmi.read_structure(task['path']), False
    if task['member']:
        if not hasattr(ZIP_LOCAL, 'archives'):
            ZIP_LOCAL.archives = {}
        if task['path'] not in ZIP_LOCAL.archives:
            ZIP_LOCAL.archives[task['path']] = zipfile.ZipFile(task['path'])
        raw = ZIP_LOCAL.archives[task['path']].read(task['member'])  # validates CRC
        task['_source_structure_sha256'] = hashlib.sha256(raw).hexdigest()
    else:
        # Do not load gigabyte-sized CAPRI ensembles into memory.
        chunks, has_models = [], False
        with open(task['path'], 'rb') as f:
            for line in f:
                if line.startswith(b'MODEL '):
                    has_models = True
                chunks.append(line)
                if line.startswith(b'ENDMDL'):
                    break
        raw = b''.join(chunks)
        return pdb_compat(raw, task), has_models
    if name.lower().endswith('.cif.gz'):
        raw = gzip.decompress(raw)
    if name.lower().endswith(('.cif', '.cif.gz')):
        return gemmi.make_structure_from_block(gemmi.cif.read_string(raw.decode('utf-8')).sole_block()), False
    return pdb_compat(raw, task), b'MODEL ' in raw

def chain_data(model):
    chains, missing, total, details = [], 0, 0, []
    for chain in model:
        coords, owners, sequence = [], [], []
        residue_names=[]; residue_atoms=[]; residue_altloc=[]; residue_min_occ=[]
        residue_mean_b=[]; residue_missing_sidechain=[]; atom_names=[]; residue_seqids=[]
        for res in chain:
            info = gemmi.find_tabulated_residue(res.name)
            if not info.is_amino_acid() or res.entity_type in (gemmi.EntityType.Water, gemmi.EntityType.NonPolymer):
                continue
            # Unknown entity type (common in PDB) is accepted for amino acids.
            observed=[atom for atom in res if atom.occ > 0 and not atom.element.is_hydrogen]
            atoms = {}
            for atom in observed:
                if not all(math.isfinite(v) for v in (atom.pos.x, atom.pos.y, atom.pos.z)):
                    raise ValueError('non-finite coordinate')
                if atom.name not in atoms or atom.occ > atoms[atom.name].occ:
                    atoms[atom.name] = atom
            if not atoms:
                continue
            rid = len(sequence)
            sequence.append(info.one_letter_code.upper())
            residue_names.append(res.name.upper())
            residue_seqids.append(str(res.seqid))
            residue_atoms.append(sorted(atoms))
            residue_altloc.append(any(str(atom.altloc).strip().strip('\x00') for atom in observed))
            residue_min_occ.append(float(min(atom.occ for atom in atoms.values())))
            bvalues=[float(atom.b_iso) for atom in atoms.values() if math.isfinite(float(atom.b_iso))]
            residue_mean_b.append(float(np.mean(bvalues)) if bvalues else math.nan)
            expected=SIDECHAIN_HEAVY.get(res.name.upper(), set())
            residue_missing_sidechain.append(sorted(expected-set(atoms)))
            absent = sorted(BACKBONE - atoms.keys())
            total += 1
            if absent:
                missing += 1
                details.append(f'{chain.name}:{res.seqid}:{res.name}({",".join(absent)})')
            for atom in atoms.values():
                coords.append((atom.pos.x, atom.pos.y, atom.pos.z))
                owners.append(rid)
                atom_names.append(atom.name)
        if coords:
            xyz = np.array(coords, dtype=np.float64)
            chains.append(dict(
                name=chain.name, sequence=''.join(sequence), xyz=xyz,
                owners=np.array(owners), tree=cKDTree(xyz), low=xyz.min(0), high=xyz.max(0),
                residue_names=residue_names, residue_atoms=residue_atoms,
                residue_seqids=residue_seqids, atom_names=atom_names,
                residue_altloc=residue_altloc, residue_min_occ=residue_min_occ,
                residue_mean_b=residue_mean_b,
                residue_missing_sidechain=residue_missing_sidechain,
            ))
    return chains, missing, total, details
