"""External VHH candidate selection and graph construction."""
from __future__ import annotations

import datetime as dt
import json

import pytest

from nanoqc.data import build_external_vhh_graphs as ext
from nanoqc.data import select_external_vhh_candidates as sel

VHH_TAIL = ("QVQLQESGGGLVQAGGSLRLSCAASGRTFSSYAMGWFRQAPGKEREFVAAISWSGGSTYYADSVKGRFTISRDNAKNTVYLQMNSL"
            "KPEDTAVYYCAAGRYGSSWYPDSYDYWGQGTQVTVSS")
VHH = "A" * 20 + VHH_TAIL
THREE = {"A": "ALA", "C": "CYS", "D": "ASP", "E": "GLU", "F": "PHE", "G": "GLY", "H": "HIS", "I": "ILE",
         "K": "LYS", "L": "LEU", "M": "MET", "N": "ASN", "P": "PRO", "Q": "GLN", "R": "ARG", "S": "SER",
         "T": "THR", "V": "VAL", "W": "TRP", "Y": "TYR"}


def _atoms(chain, sequence, x0, z, serial):
    lines = []
    for i, aa in enumerate(sequence):
        x = x0 + 3.8 * i
        atoms = [("N", x, 0.0), ("CA", x + 1.2, 0.8), ("C", x + 2.4, 0.0), ("O", x + 2.4, -1.2)]
        if aa != "G":
            atoms.append(("CB", x + 1.2, 2.0))
        for name, ax, ay in atoms:
            serial += 1
            lines.append(f"ATOM  {serial:5d}  {name:<3s} {THREE[aa]} {chain}{i + 1:4d}    "
                         f"{ax:8.3f}{ay:8.3f}{z:8.3f}  1.00 20.00           {name[0]}")
    return lines, serial


def _complex_pdb(antigen_raw_z: float, antigen_shift: float) -> str:
    """VHH H at z=0; antigen A generated by a -shift z translation; far chain C."""
    head = ["REMARK   2 RESOLUTION.    2.00 ANGSTROMS.",
            "REMARK 350 BIOMOLECULE: 1",
            "REMARK 350 AUTHOR DETERMINED BIOLOGICAL UNIT: TRIMERIC",
            "REMARK 350 APPLY THE FOLLOWING TO CHAINS: H, C",
            "REMARK 350   BIOMT1   1  1.000000  0.000000  0.000000        0.00000",
            "REMARK 350   BIOMT2   1  0.000000  1.000000  0.000000        0.00000",
            "REMARK 350   BIOMT3   1  0.000000  0.000000  1.000000        0.00000",
            "REMARK 350 APPLY THE FOLLOWING TO CHAINS: A",
            "REMARK 350   BIOMT1   2  1.000000  0.000000  0.000000        0.00000",
            "REMARK 350   BIOMT2   2  0.000000  1.000000  0.000000        0.00000",
            f"REMARK 350   BIOMT3   2  0.000000  0.000000  1.000000 {-antigen_shift:14.5f}"]
    body, serial = _atoms("H", VHH, 0.0, 0.0, 0)
    more, serial = _atoms("A", "A" * 18, 3.8, antigen_raw_z, serial)
    body += more + ["TER"]
    more, serial = _atoms("C", "A" * 10, 0.0, 60.0, serial)
    body += more
    return "\n".join(head + body + ["TER", "END"]) + "\n"


def test_cdr3_is_located_between_imgt_anchor_motifs():
    assert ext.cdr3_by_motif(VHH_TAIL) == "AAGRYGSSWYPDSYDY"
    with pytest.raises(ValueError, match="FR4"):
        ext.cdr3_by_motif("QVQLVESGGGLVQAGGSLRLSCAAS")


def test_optional_anarci_numbering_is_used_when_installed(monkeypatch):
    import sys
    import types

    numbered = [((n, " "), aa) for n, aa in zip(range(1, 129), VHH_TAIL)]
    fake = types.ModuleType("anarci")
    fake.anarci = lambda seqs, scheme, output: ([[(numbered, 0, 0)]], None, None)
    monkeypatch.setitem(sys.modules, "anarci", fake)
    cdrs = ext.annotate_cdrs(VHH_TAIL)
    assert cdrs["method"] == "anarci_imgt"
    assert cdrs["cdr3"] == VHH_TAIL[104:117] and cdrs["cdr1"] == VHH_TAIL[26:38]


def test_external_complex_builds_a_verified_v18_graph(tmp_path, monkeypatch):
    import sys
    monkeypatch.setitem(sys.modules, "anarci", None)  # force the motif fallback
    from nanoqc.data.audit_external_vhh_independence import graph_sequences
    structures = tmp_path / "structures"
    structures.mkdir()
    source = structures / "9zzz.pdb"
    source.write_text(_complex_pdb(antigen_raw_z=104.5, antigen_shift=100.0))

    prepared = ext.prepare_external_complex(source, "H")
    assert prepared["antigen_chains"] == ["A-2"]  # symmetry-generated antigen is kept
    assert {d["chain"] for d in prepared["meta"]["dropped_chains"]} == {"C"}
    assert prepared["meta"]["antigen_contact_basis"] == "whole_vhh_chain_cdr_unmapped"
    assert prepared["cdrs"] == dict(cdr1="", cdr2="", cdr3="AAGRYGSSWYPDSYDY", method="imgt_anchor_motif")
    quality = prepared["quality"]
    assert quality["structure_quality_status"] == "pass", quality
    assert quality["interface_residues"] >= 15

    graph = ext.build_graph(prepared, "9zzz", source)
    assert graph.graph_version == "1.8" and graph.subset_source == "external_vhh"
    assert graph.structure_source == "biological_assembly:author_determined:1"
    import torch
    out = tmp_path / "graphs"
    out.mkdir()
    torch.save(graph, out / "external_vhh__9ZZZ.pt")
    # The formal audit's raw-structure check must rebuild the same assembly.
    record = graph_sequences(out / "external_vhh__9ZZZ.pt", structures)
    assert record["pdb_id"] == "9zzz" and record["cdr_h3"] == "AAGRYGSSWYPDSYDY"
    assert record["vhh"] == [VHH]


def test_quality_gate_rejects_poor_resolution(tmp_path, monkeypatch):
    import sys
    monkeypatch.setitem(sys.modules, "anarci", None)
    source = tmp_path / "9zzy.pdb"
    source.write_text(_complex_pdb(104.5, 100.0).replace("2.00 ANGSTROMS", "3.50 ANGSTROMS"))
    prepared = ext.prepare_external_complex(source, "H")
    assert prepared["quality"]["structure_quality_reasons"] == ["resolution_above_limit"]
    with pytest.raises(ValueError, match="structure quality failed"):
        ext.build_graph(prepared, "9zzy", source)


def _sabdab(**over):
    row = dict(pdb="9abc", Hchain="B", Lchain="NA", antigen_chain="A", antigen_type="protein",
               antigen_name="thing", date="07/29/26", resolution="2.1", method="X-RAY DIFFRACTION", scfv="False")
    row.update(over)
    return row


def test_metadata_gate_mirrors_training_vhh_rules():
    cutoff = dt.date(2026, 1, 1)
    ok = sel.metadata_gate("9abc", [_sabdab()], released_after=cutoff, excluded=set(), max_resolution=3.0)
    assert ok["reasons"] == [] and ok["vhh_chain"] == "B" and ok["release_date"] == "2026-07-29"
    two_vhh = sel.metadata_gate("9abc", [_sabdab(), _sabdab(Hchain="C")], released_after=cutoff,
                                excluded=set(), max_resolution=3.0)
    assert "vhh_chain_count_not_one" in two_vhh["reasons"]
    fab = sel.metadata_gate("9abc", [_sabdab(), _sabdab(Hchain="H", Lchain="L")], released_after=cutoff,
                            excluded=set(), max_resolution=3.0)
    assert "contains_vh_vl_antibody" in fab["reasons"]
    old = sel.metadata_gate("9abc", [_sabdab(date="2025-06-01", resolution="NA", antigen_type="carbohydrate")],
                            released_after=cutoff, excluded={"9abc"}, max_resolution=3.0)
    assert {"released_before_cutoff", "unknown_resolution", "non_protein_antigen", "in_study_universe"} <= set(old["reasons"])


def test_independent_groups_use_the_layered_rule_and_structure_clusters():
    base = dict(vhh_sequence=VHH, cdr3="AAGRYGSSWYPDSYDY", antigen_sequences=["MKTAYIAKQRQISFVKSHFSRQ" * 5])
    rows = [dict(base, pdb_id="1aaa"),
            dict(base, pdb_id="2bbb"),  # same complex: one group
            dict(pdb_id="3ccc", vhh_sequence="EVQLVESGGGSVQPGGSLKLSCVAS" * 4, cdr3="NVKDYGTRW",
                 antigen_sequences=["GSHMLEDPVDAFQSWLDNEEAKKALEDKAKSDGRLL" * 3]),
            dict(pdb_id="4ddd", vhh_sequence="DVQLQASGGGLAQPGESLRLSCKTS" * 4, cdr3="RRDSPLGQW",
                 antigen_sequences=["PPKKQIVEVLERFLKEHPAYKEDVIEL" * 4])]
    thresholds = dict(vhh=0.8, cdr=0.5, antigen=0.3, coverage=0.7)
    groups = sel.independent_groups(rows, {}, **thresholds)
    assert groups["1aaa"] == groups["2bbb"] and len(set(groups.values())) == 3
    merged = sel.independent_groups(rows, {"3ccc": "c1", "4ddd": "c1"}, **thresholds)
    assert len(set(merged.values())) == 2


def test_selection_cli_reports_cluster_adequacy(tmp_path, monkeypatch):
    import sys
    monkeypatch.setitem(sys.modules, "anarci", None)
    structures = tmp_path / "structures"
    structures.mkdir()
    (structures / "9zzz.pdb").write_text(_complex_pdb(104.5, 100.0))
    summary = tmp_path / "sabdab.tsv"
    rows = [_sabdab(pdb="9zzz", Hchain="H"), _sabdab(pdb="9yyy", Hchain="H", date="01/02/20")]
    keys = list(rows[0])
    summary.write_text("\t".join(keys) + "\n" + "".join("\t".join(r[k] for k in keys) + "\n" for r in rows))
    out = tmp_path / "selection"
    sel.main(["--sabdab-summary", str(summary), "--released-after", "2026-01-01",
              "--structures-dir", str(structures), "--min-clusters", "2", "--out-dir", str(out)])
    payload = json.loads((out / "candidates.json").read_text())
    assert payload["selected"] == 1 and payload["independent_groups"] == 1 and payload["adequate"] is False
    chosen = {c["pdb_id"]: c for c in payload["candidates"]}
    assert chosen["9zzz"]["selected"] and chosen["9zzz"]["antigen_chains"] == ["A-2"]
    assert chosen["9yyy"]["reasons"] == ["released_before_cutoff"]

    graphs = tmp_path / "graphs"
    assert ext.main(["--candidates", str(out / "candidates.json"), "--structures-dir", str(structures),
                     "--out-dir", str(graphs)]) == 0
    manifest = json.loads((graphs / "external_graph_manifest.json").read_text())
    assert [g["pdb_id"] for g in manifest["graphs"]] == ["9zzz"] and manifest["failures"] == []
