"""External VHH candidate selection and graph construction."""
from __future__ import annotations

import datetime as dt
import json

import pytest

from nanoqc.data import build_external_vhh_graphs as ext
from nanoqc.data import select_external_vhh_candidates as sel

VHH_TAIL = ("QVQLQESGGGLVQAGGSLRLSCAASGRTFSSYAMGWFRQAPGKEREFVAAISWSGGSTYYADSVKGRFTISRDNAKNTVYLQMNSL"
            "KPEDTAVYYCAAGRYGSSWYPDSYDYWGQGTQVTVSS")
VHH = "A" * 20 + VHH_TAIL
THREE = {"A": "ALA", "C": "CYS", "D": "ASP", "E": "GLU", "F": "PHE", "G": "GLY", "H": "HIS", "I": "ILE",
         "K": "LYS", "L": "LEU", "M": "MET", "N": "ASN", "P": "PRO", "Q": "GLN", "R": "ARG", "S": "SER",
         "T": "THR", "V": "VAL", "W": "TRP", "Y": "TYR"}


def _atoms(chain, sequence, x0, z, serial):
    lines = []
    for i, aa in enumerate(sequence):
        x = x0 + 3.8 * i
        atoms = [("N", x, 0.0), ("CA", x + 1.2, 0.8), ("C", x + 2.4, 0.0), ("O", x + 2.4, -1.2)]
        if aa != "G":
            atoms.append(("CB", x + 1.2, 2.0))
        for name, ax, ay in atoms:
            serial += 1
            lines.append(f"ATOM  {serial:5d}  {name:<3s} {THREE[aa]} {chain}{i + 1:4d}    "
                         f"{ax:8.3f}{ay:8.3f}{z:8.3f}  1.00 20.00           {name[0]}")
    return lines, serial


def _complex_pdb(antigen_raw_z: float, antigen_shift: float, c_z: float = 60.0,
                 vhh: str = VHH, antigen: str = "A" * 18) -> str:
    """VHH H at z=0; antigen A generated by a -shift z translation; far chain C."""
    head = ["REMARK   2 RESOLUTION.    2.00 ANGSTROMS.",
            "REMARK 350 BIOMOLECULE: 1",
            "REMARK 350 AUTHOR DETERMINED BIOLOGICAL UNIT: TRIMERIC",
            "REMARK 350 APPLY THE FOLLOWING TO CHAINS: H, C",
            "REMARK 350   BIOMT1   1  1.000000  0.000000  0.000000        0.00000",
            "REMARK 350   BIOMT2   1  0.000000  1.000000  0.000000        0.00000",
            "REMARK 350   BIOMT3   1  0.000000  0.000000  1.000000        0.00000",
            "REMARK 350 APPLY THE FOLLOWING TO CHAINS: A",
            "REMARK 350   BIOMT1   2  1.000000  0.000000  0.000000        0.00000",
            "REMARK 350   BIOMT2   2  0.000000  1.000000  0.000000        0.00000",
            f"REMARK 350   BIOMT3   2  0.000000  0.000000  1.000000 {-antigen_shift:14.5f}"]
    body, serial = _atoms("H", vhh, 0.0, 0.0, 0)
    more, serial = _atoms("A", antigen, 3.8, antigen_raw_z, serial)
    body += more + ["TER"]
    more, serial = _atoms("C", "A" * 10, 0.0, c_z, serial)
    body += more
    return "\n".join(head + body + ["TER", "END"]) + "\n"


def test_cdr3_is_located_between_imgt_anchor_motifs():
    assert ext.cdr3_by_motif(VHH_TAIL) == "AAGRYGSSWYPDSYDY"
    with pytest.raises(ValueError, match="FR4"):
        ext.cdr3_by_motif("QVQLVESGGGLVQAGGSLRLSCAAS")


def test_optional_anarci_numbering_is_used_when_installed(monkeypatch):
    import sys
    import types

    numbered = [((n, " "), aa) for n, aa in zip(range(1, 129), VHH_TAIL)]
    fake = types.ModuleType("anarci")
    fake.anarci = lambda seqs, scheme, output: ([[(numbered, 0, 0)]], None, None)
    monkeypatch.setitem(sys.modules, "anarci", fake)
    cdrs = ext.annotate_cdrs(VHH_TAIL)
    assert cdrs["method"] == "anarci_imgt"
    assert cdrs["cdr3"] == VHH_TAIL[104:117] and cdrs["cdr1"] == VHH_TAIL[26:38]


def test_external_complex_builds_a_verified_v18_graph(tmp_path, monkeypatch):
    import sys
    monkeypatch.setitem(sys.modules, "anarci", None)  # force the motif fallback
    from nanoqc.data.audit_external_vhh_independence import graph_sequences
    structures = tmp_path / "structures"
    structures.mkdir()
    source = structures / "9zzz.pdb"
    source.write_text(_complex_pdb(antigen_raw_z=104.5, antigen_shift=100.0))

    prepared = ext.prepare_external_complex(source, "H")
    assert prepared["antigen_chains"] == ["A-2"]  # symmetry-generated antigen is kept
    assert {d["chain"] for d in prepared["meta"]["dropped_chains"]} == {"C"}
    assert prepared["meta"]["antigen_contact_basis"] == "whole_vhh_chain_cdr_unmapped"
    assert prepared["cdrs"] == dict(cdr1="", cdr2="", cdr3="AAGRYGSSWYPDSYDY", method="imgt_anchor_motif")
    quality = prepared["quality"]
    assert quality["structure_quality_status"] == "pass", quality
    assert quality["interface_residues"] >= 15

    graph = ext.build_graph(prepared, "9zzz", source)
    assert graph.graph_version == "1.8" and graph.subset_source == "external_vhh"
    assert graph.structure_source == "biological_assembly:author_determined:1"
    import torch
    out = tmp_path / "graphs"
    out.mkdir()
    torch.save(graph, out / "external_vhh__9ZZZ.pt")
    # The formal audit's raw-structure check must rebuild the same assembly.
    record = graph_sequences(out / "external_vhh__9ZZZ.pt", structures)
    assert record["pdb_id"] == "9zzz" and record["cdr_h3"] == "AAGRYGSSWYPDSYDY"
    assert record["vhh"] == [VHH]


def test_quality_gate_rejects_poor_resolution(tmp_path, monkeypatch):
    import sys
    monkeypatch.setitem(sys.modules, "anarci", None)
    source = tmp_path / "9zzy.pdb"
    source.write_text(_complex_pdb(104.5, 100.0).replace("2.00 ANGSTROMS", "3.50 ANGSTROMS"))
    prepared = ext.prepare_external_complex(source, "H")
    assert prepared["quality"]["structure_quality_reasons"] == ["resolution_above_limit"]
    with pytest.raises(ValueError, match="structure quality failed"):
        ext.build_graph(prepared, "9zzy", source)


def _sabdab(**over):
    row = dict(pdb="9abc", Hchain="B", Lchain="NA", antigen_chain="A", antigen_type="protein",
               antigen_name="thing", date="07/29/26", resolution="2.1", method="X-RAY DIFFRACTION", scfv="False")
    row.update(over)
    return row


def test_metadata_gate_mirrors_training_vhh_rules():
    cutoff = dt.date(2026, 1, 1)
    ok = sel.metadata_gate("9abc", [_sabdab()], released_after=cutoff, excluded=set(), max_resolution=3.0)
    assert ok["reasons"] == [] and ok["vhh_chains"] == ["B"] and ok["release_date"] == "2026-07-29"
    two_vhh = sel.metadata_gate("9abc", [_sabdab(), _sabdab(Hchain="C")], released_after=cutoff,
                                excluded=set(), max_resolution=3.0)
    assert two_vhh["reasons"] == [] and two_vhh["vhh_chains"] == ["B", "C"]
    fab = sel.metadata_gate("9abc", [_sabdab(), _sabdab(Hchain="H", Lchain="L")], released_after=cutoff,
                            excluded=set(), max_resolution=3.0)
    assert "contains_vh_vl_antibody" in fab["reasons"]
    old = sel.metadata_gate("9abc", [_sabdab(date="2025-06-01", resolution="NA", antigen_type="carbohydrate")],
                            released_after=cutoff, excluded={"9abc"}, max_resolution=3.0)
    assert {"released_before_cutoff", "unknown_resolution", "non_protein_antigen", "in_study_universe"} <= set(old["reasons"])


def test_independent_groups_use_the_layered_rule_and_structure_clusters():
    base = dict(vhh_sequence=VHH, cdr3="AAGRYGSSWYPDSYDY", antigen_sequences=["MKTAYIAKQRQISFVKSHFSRQ" * 5])
    rows = [dict(base, pdb_id="1aaa"),
            dict(base, pdb_id="2bbb"),  # same complex: one group
            dict(pdb_id="3ccc", vhh_sequence="EVQLVESGGGSVQPGGSLKLSCVAS" * 4, cdr3="NVKDYGTRW",
                 antigen_sequences=["GSHMLEDPVDAFQSWLDNEEAKKALEDKAKSDGRLL" * 3]),
            dict(pdb_id="4ddd", vhh_sequence="DVQLQASGGGLAQPGESLRLSCKTS" * 4, cdr3="RRDSPLGQW",
                 antigen_sequences=["PPKKQIVEVLERFLKEHPAYKEDVIEL" * 4])]
    thresholds = dict(vhh=0.8, cdr=0.5, antigen=0.3, coverage=0.7)
    groups = sel.independent_groups(rows, {}, **thresholds)
    assert groups["1aaa"] == groups["2bbb"] and len(set(groups.values())) == 3
    merged = sel.independent_groups(rows, {"3ccc": "c1", "4ddd": "c1"}, **thresholds)
    assert len(set(merged.values())) == 2


def test_selection_cli_reports_cluster_adequacy(tmp_path, monkeypatch):
    import sys
    monkeypatch.setitem(sys.modules, "anarci", None)
    structures = tmp_path / "structures"
    structures.mkdir()
    (structures / "9zzz.pdb").write_text(_complex_pdb(104.5, 100.0))
    summary = tmp_path / "sabdab.tsv"
    rows = [_sabdab(pdb="9zzz", Hchain="H"), _sabdab(pdb="9yyy", Hchain="H", date="01/02/20")]
    keys = list(rows[0])
    summary.write_text("\t".join(keys) + "\n" + "".join("\t".join(r[k] for k in keys) + "\n" for r in rows))
    out = tmp_path / "selection"
    sel.main(["--sabdab-summary", str(summary), "--released-after", "2026-01-01",
              "--structures-dir", str(structures), "--min-clusters", "2", "--out-dir", str(out)])
    payload = json.loads((out / "candidates.json").read_text())
    assert payload["selected"] == 1 and payload["independent_groups"] == 1 and payload["adequate"] is False
    chosen = {c["pdb_id"]: c for c in payload["candidates"]}
    assert chosen["9zzz"]["selected"] and chosen["9zzz"]["antigen_chains"] == ["A-2"]
    assert chosen["9yyy"]["reasons"] == ["released_before_cutoff"]

    graphs = tmp_path / "graphs"
    assert ext.main(["--candidates", str(out / "candidates.json"), "--structures-dir", str(structures),
                     "--out-dir", str(graphs)]) == 0
    manifest = json.loads((graphs / "external_graph_manifest.json").read_text())
    assert [g["pdb_id"] for g in manifest["graphs"]] == ["9zzz"] and manifest["failures"] == []


def test_other_nanobodies_are_never_antigen_and_one_vhh_is_chosen(tmp_path, monkeypatch):
    import sys
    monkeypatch.setitem(sys.modules, "anarci", None)
    source = tmp_path / "9zzx.pdb"
    source.write_text(_complex_pdb(104.5, 100.0, c_z=-4.5))  # chain C now touches the VHH
    plain = ext.prepare_external_complex(source, "H")
    assert sorted(plain["antigen_chains"]) == ["A-2", "C"]
    prepared, attempts = sel.choose_vhh(source, ["C", "H"])
    assert prepared["vhh_chain"] == "H" and prepared["antigen_chains"] == ["A-2"]
    assert {"chain": "C", "reason": "other_antibody_chain"} in prepared["meta"]["dropped_chains"]
    assert [a["vhh_chain"] for a in attempts] == ["C", "H"] and attempts[0]["reasons"]


def test_cdr3_agreement_is_measured_on_snac_training_annotations(monkeypatch):
    import sys
    monkeypatch.setitem(sys.modules, "anarci", None)
    train = [dict(subset_source="snac_db", vhh=[VHH_TAIL], cdr_h3="AAGRYGSSWYPDSYDY"),
             dict(subset_source="snac_db", vhh=[VHH_TAIL], cdr_h3="GRYGSSWYPDSYDY"),
             dict(subset_source="train_rcsb", vhh=[VHH_TAIL], cdr_h3="AAGRYGSSWYPDSYDY")]
    assert sel.cdr3_method_agreement(train) == dict(compared=2, agreed=1, fraction=0.5,
                                                    methods=["imgt_anchor_motif"])


OTHER_VHH = "A" * 20 + ("EVQLVESGGGSVQPGGSLKLSCVASGFTLDDYAIGWFRQAPGKEREGVSCISSSDGSTYYADSVKGRFTISRDNAKNTVYLQMNS"
                        "LKPEDTAVYYCAKDPRWGGCYYGMDYWGKGTLVTVSS")


def test_two_pass_preparation_keeps_the_universe_and_pair_table_fixed(tmp_path, monkeypatch):
    import sys
    import torch
    import yaml
    from pathlib import Path as P
    from nanoqc.common.repo_io import sha256_file
    from nanoqc.data import prepare_external_vhh as prep

    monkeypatch.setitem(sys.modules, "anarci", None)
    monkeypatch.setenv("PYTHONPATH", str(P(__file__).resolve().parents[1] / "src"))
    monkeypatch.delenv("QP_EXTERNAL_VHH_SOURCE_DIR", raising=False)
    structures = tmp_path / "structures"
    structures.mkdir()
    (structures / "9zzz.pdb").write_text(_complex_pdb(104.5, 100.0))
    pairs = tmp_path / "pairs.tsv"
    pairs.write_text("query\ttarget\tqtmscore\n1abc\t1abc\t1.0\n9zzz\t9zzz\t1.0\n")
    config = dict(paths=dict(data_root=str(tmp_path / "data"), dataset_dir="dataset"),
                  data_audit=dict(max_resolution_angstrom=3.0),
                  queue_freeze=dict(homology_isolation=dict(vhh_full_chain_identity=0.8, cdr_h3_identity=0.5,
                                                            antigen_identity=0.3, antigen_min_length_coverage=0.7),
                                    independence_clustering=dict(pair_tsv=str(pairs))),
                  external_validation=dict(external_vhh=dict(graph_dir=str(tmp_path / "graphs"),
                                                             source_structure_dir=str(structures), min_clusters=1)))
    config_path = tmp_path / "config.yaml"
    config_path.write_text(yaml.safe_dump(config))
    prep_dir = tmp_path / "prep"
    prep_dir.mkdir()
    (prep_dir / "study_pdb_ids.txt").write_text("1abc\n")
    summary = tmp_path / "sabdab.tsv"
    row = _sabdab(pdb="9zzz", Hchain="H")
    summary.write_text("\t".join(row) + "\n" + "\t".join(row.values()) + "\n")
    common = ["--config", str(config_path), "--prep-dir", str(prep_dir)]
    select = ["--sabdab-summary", str(summary), "--released-after", "2026-01-01"]

    assert prep.main(common + ["pass1", *select]) == 0
    assert (prep_dir / "foldseek_universe.txt").read_text().split() == ["1abc", "9zzz"]
    assert json.loads((prep_dir / "pass1_record.json").read_text())["external_pdb_ids"] == ["9zzz"]

    # A queue_freeze run: non-overlapping training graph + cluster map built from the same pair table.
    run = tmp_path / "run"
    train_dir = run / "dataset" / "graphs" / "train"
    train_dir.mkdir(parents=True)
    train_src = tmp_path / "1abc.pdb"
    train_src.write_text(_complex_pdb(104.5, 100.0, vhh=OTHER_VHH, antigen="G" * 18))
    graph = ext.build_graph(ext.prepare_external_complex(train_src, "H"), "1abc", train_src)
    torch.save(graph, train_dir / "t.pt")
    (run / "dataset" / "graph_manifest.json").write_text(json.dumps([dict(
        split="train", path="graphs/train/t.pt", sha256=sha256_file(train_dir / "t.pt"), pdb_id="1ABC")]))
    (run / "independence").mkdir()
    (run / "independence" / "pdb_family_clusters.json").write_text(json.dumps({"1abc": "c1", "9zzz": "c2"}))
    (run / "independence" / "pdb_family_clusters.provenance.json").write_text(
        json.dumps(dict(source_pairs_sha256=sha256_file(pairs))))

    assert prep.main(common + ["pass2", *select, "--run-dir", str(run)]) == 0
    record = json.loads((prep_dir / "pass2_record.json").read_text())
    assert record["external_pdb_ids"] == ["9zzz"] and record["dropped_after_training_check"] == []
    assert list((tmp_path / "graphs").glob("*.pt")) and list(prep_dir.glob("graphs_backup_*"))

    pairs.write_text(pairs.read_text() + "1abc\t9zzz\t0.1\n")  # the table must not change between passes
    with pytest.raises(SystemExit, match="pair table differs"):
        prep.main(common + ["pass2", *select, "--run-dir", str(run)])


FAKE_FOLDSEEK = r'''#!{python}
import sys, pathlib, gemmi
if sys.argv[1] == "version":
    print("fake-foldseek 1"); sys.exit(0)
assert sys.argv[1] == "easy-search"
inputs, out = pathlib.Path(sys.argv[2]), pathlib.Path(sys.argv[4])
entries = [(f.name, c.name) for f in sorted(inputs.iterdir()) for c in gemmi.read_structure(str(f))[0]]
with out.open("w") as handle:
    for qf, qc in entries:
        for tf, tc in entries:
            handle.write(f"{qf}_{qc}\t{tf}_{tc}\t{1.0 if qf == tf else 0.2}\n")
'''


def test_foldseek_pairs_use_antigen_chains_only(tmp_path, monkeypatch):
    import os
    import subprocess
    import sys
    from pathlib import Path as P
    from nanoqc.data import build_foldseek_pairs as fp

    monkeypatch.setitem(sys.modules, "anarci", None)
    raw = tmp_path / "raw"
    raw.mkdir()

    def write(name, chains):
        lines, serial = [], 0
        for chain, sequence, z in chains:
            more, serial = _atoms(chain, sequence, 0.0, z, serial)
            lines += more + ["TER"]
        (raw / name).write_text("\n".join(lines + ["END"]) + "\n")
        return str(raw / name)

    antigen = "MKTAYIAKQRQISFVKSHFSRQ"
    rows = [dict(pdb_id="1ABC", path=write("1abc.pdb", [("H", VHH_TAIL, 0.0), ("A", antigen, 6.0)]), subset="train_rcsb"),
            dict(pdb_id="2DEF", path=write("2def.pdb", [("H", VHH_TAIL, 0.0)]), subset="sabdab_vhh"),
            dict(pdb_id="3GHI", path=write("3ghi_r_b.pdb", [("R", antigen, 0.0)]), subset="test_db55"),
            dict(pdb_id="3GHI", path=write("3ghi_r_u.pdb", [("U", "G" * 30, 0.0)]), subset="test_db55")]
    audit_dir = tmp_path / "audit"
    audit_dir.mkdir()
    (audit_dir / "data_audit_details.jsonl").write_text(
        "".join(json.dumps(dict(r, member="", id=P(r["path"]).name)) + "\n" for r in rows))
    structures = tmp_path / "structures"
    structures.mkdir()
    (structures / "9zzz.pdb").write_text(_complex_pdb(104.5, 100.0))
    candidates = tmp_path / "candidates.json"
    candidates.write_text(json.dumps(dict(candidates=[dict(pdb_id="9zzz", selected=True, vhh_chain="H",
                                                            vhh_chains=["H"])])))
    universe = tmp_path / "universe.txt"
    universe.write_text("1abc\n2def\n3ghi\n9zzz\n")
    fake = tmp_path / "foldseek"
    fake.write_text(FAKE_FOLDSEEK.replace("{python}", sys.executable))
    fake.chmod(0o755)
    out = tmp_path / "pairs.tsv"
    argv = ["--universe", str(universe), "--audit-dir", str(audit_dir), "--data-root", str(tmp_path / "none"),
            "--external-candidates", str(candidates), "--external-structures", str(structures),
            "--out", str(out), "--work-dir", str(tmp_path / "work"), "--foldseek", str(fake)]
    assert fp.main(argv) == 0

    lines = out.read_text().splitlines()
    assert lines[0] == "query\ttarget\tqtmscore"
    pairs = {tuple(line.split("\t")[:2]): float(line.split("\t")[2]) for line in lines[1:]}
    assert pairs[("2def", "2def")] == 1.0 and not any("2def" in p and p != ("2def", "2def") for p in pairs)
    assert pairs[("1abc", "3ghi")] == 0.2
    manifest = json.loads(out.with_suffix(".manifest.json").read_text())
    assert manifest["self_only"] == ["2def", "9zzz"] and manifest["foldseek_version"] == "fake-foldseek 1"
    roles = {(pdb, c["chain"]): (c["role"], c["method"]) for pdb, r in manifest["per_pdb"].items() for c in r["chains"]}
    assert roles[("1abc", "H")] == ("antibody", "v_domain_motif")
    assert roles[("1abc", "A")] == ("antigen", "v_domain_motif")
    assert roles[("9zzz", "H")] == ("antibody", "sabdab_chain_id")
    assert roles[("9zzz", "A")] == ("skipped", "shorter_than_20")
    assert ("3ghi", "U") not in roles  # DB5.5: bound files only

    env = dict(os.environ, PYTHONPATH=str(P(__file__).resolve().parents[1] / "src"))
    cluster = tmp_path / "clusters.json"
    subprocess.run([sys.executable, "-m", "nanoqc.data.build_independence_cluster_map", "--pairs", str(out),
                    "--out-json", str(cluster), "--min-score", "0.5", "--score-semantics", "qtmscore",
                    "--universe", str(universe)], check=True, env=env)
    clusters = json.loads(cluster.read_text())
    assert len(set(clusters.values())) == 4  # 0.2 < 0.5: no edges between different PDBs
    assert manifest["per_pdb"]["9zzz"]["self_only_reason"] == "no_antigen_chain_for_structure_search"

    with pytest.raises(SystemExit, match="frozen"):
        fp.main(argv)


def test_v_domain_motif_separates_antibodies_from_ig_superfamily_antigens():
    from nanoqc.data.build_foldseek_pairs import ig_variable_domain_by_motif as detect
    vl = ("DIQMTQSPSSLSASVGDRVTITCRASQDVNTAVAWYQQKPGKAPKLLIYSASFLYSGVPSRFSGSRSGTDFTLTISSLQPEDFATYYCQQHYT"
          "TPPTFGQGTKVEIK")
    pd1 = ("PGWFLDSPDRPWNPPTFSPALLVVTEGDNATFTCSFSNTSESFVLNWYRMSPSNQTDKLAAFPEDRSQPGQDCRFRVTQLPNGRDFHMSVVRA"
           "RRNDSGTYLCGAISLAPKAQIKESLRAELRVTERRAE")
    assert detect(VHH_TAIL) and detect(vl) and not detect(pd1)
