#!/usr/bin/env python3
"""Read-only pilot: compare raw and fixed-backbone-relaxed Amber energies.

Uses rows already generated by a failed calibration run. All temporary
structures are written outside the run directory and removed on exit.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import tempfile
from pathlib import Path

import gemmi
import numpy as np

from nanoqc.data.audit_all_datasets import materialize_graph_complex
from nanoqc.data.safe_graph_load import load_graph
from nanoqc.experiments.generate_energy_calibration_dataset import _manifest_graph_path
from nanoqc.experiments.run_real_complex_pilot import (
    complete_terminal_oxygen,
    strip_to_protein_conformer,
)
from nanoqc.qubo.subgraph_to_qubo import AllAtomInterfaceQUBOBuilder, read_atomistic_structure
from nanoqc.reporting.generate_figure1_pymol_script import extract_source


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run-dir", type=Path, required=True)
    parser.add_argument("--limit", type=int, default=4)
    parser.add_argument("--iterations", type=int, default=200)
    args = parser.parse_args()
    if args.limit < 2 or args.iterations < 1:
        parser.error("--limit must be >=2 and --iterations must be >=1")

    run_dir = args.run_dir.resolve(strict=True)
    config = json.loads((run_dir / "run_manifest.json").read_text(encoding="utf-8"))["config"]
    data_root = Path(config["paths"]["data_root"])
    if not data_root.is_absolute():
        data_root = Path(config["paths"]["repo_root"]) / data_root
    dataset = run_dir / config["paths"].get("dataset_dir", "dataset")
    csv_path = run_dir / config["qc_benchmark"]["energy_calibration"]["training_csv"]
    with csv_path.open(newline="", encoding="utf-8-sig") as handle:
        rows = list(csv.DictReader(handle))
    if not rows:
        raise ValueError("Calibration CSV has no rows")

    # The strongest recorded failure selects the diagnostic complex. Include
    # its anchor and both early and extreme assignments, without changing data.
    extreme = max(rows, key=lambda row: abs(float(row["amber_delta_kcal"])))
    group = [row for row in rows if row["graph_sha256"] == extreme["graph_sha256"]]
    anchor = next(row for row in group if int(row["assignment_index"]) == 0)
    selected = [anchor]
    selected.extend(row for row in sorted(group, key=lambda r: int(r["assignment_index"]))
                    if row is not anchor and len(selected) < max(2, args.limit // 2))
    selected.extend(row for row in sorted(group, key=lambda r: -abs(float(r["amber_delta_kcal"])))
                    if row not in selected and len(selected) < args.limit)

    manifest = json.loads((dataset / "graph_manifest.json").read_text(encoding="utf-8"))
    graph_row = next(row for row in manifest if row.get("sha256") == extreme["graph_sha256"])
    graph = load_graph(_manifest_graph_path(dataset, graph_row["path"]))
    active = json.loads(anchor["active_residues"])

    with tempfile.TemporaryDirectory(prefix="calibration_relax_pilot_") as temp_name:
        temp = Path(temp_name)
        source = extract_source(graph.source_id, data_root, temp / "raw_structure")
        source = materialize_graph_complex(source, graph, temp / "graph_complex.cif")
        structure = gemmi.read_structure(str(source))
        while len(structure) > 1:
            del structure[1]
        model_one = temp / "model1.cif"
        structure.make_mmcif_document().write_file(str(model_one))
        residues = read_atomistic_structure(model_one)
        if set(residues) != set(graph.residue_ids):
            raise ValueError("Raw/graph protein residue identities differ")
        for index, rid in enumerate(graph.residue_ids):
            if not np.allclose(residues[rid]["atoms"]["CA"], graph.pos[index].numpy(), atol=.002):
                raise ValueError(f"Raw/graph coordinates differ at {rid}")
        strip_to_protein_conformer(structure, residues)
        local = temp / "native.cif"
        structure.make_mmcif_document().write_file(str(local))
        complete_terminal_oxygen(local)
        builder = AllAtomInterfaceQUBOBuilder(
            local, active, chi1_angles=(-60., 60., 180.), rotamer_mode="legacy",
            solvent_model=config["structure_experiment"].get("solvent_model", "vacuum"),
        )
        print(json.dumps({"pdb_id": extreme["pdb_id"], "source_id": extreme["source_id"],
                          "graph_sha256": extreme["graph_sha256"], "assignments": len(selected),
                          "iterations": args.iterations, "mode": "read_only_diagnostic"}))
        anchor_relaxed = None
        for row in selected:
            index = int(row["assignment_index"])
            assignment = json.loads(row["chi_assignment"])
            positions = builder.positions_for_chi_assignment(assignment)
            raw = builder.energy(positions)
            recorded = float(row["anchor_amber_kcal"]) + float(row["amber_delta_kcal"])
            if not math.isclose(raw, recorded, rel_tol=1e-8, abs_tol=1e-3):
                raise ValueError(f"Recomputed raw energy differs from frozen CSV at row {index}")
            result = builder.relax_positions(
                positions, temp / f"assignment_{index}.cif",
                minimize_iterations=args.iterations,
            )
            relaxed = float(result["relaxed_energy_kcal"])
            if index == 0:
                anchor_relaxed = relaxed
            print(json.dumps({"assignment_index": index, "raw_kcal": raw,
                              "relaxed_kcal": relaxed,
                              "relaxed_delta_kcal": relaxed - anchor_relaxed,
                              "recorded_delta_kcal": float(row["amber_delta_kcal"])}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
